### ISSUE TITLE
Read the Shortcut-Values like the Powershell?

### ISSUE THREAD

**Issue by cyberpunkbln** [lilopkins/lnk-rs#1]
Hello,

very cool Rust-Lib. Is it possible to easy implement functions in save and read lnk for the other values like target, icon, execute in path and the others?

```
let shortcut = lnk::ShellLink::open(args[1].as_str()).unwrap();
println!("{:?}", shortcut.target);
```

thx

**Comment by lilopkins** [comment]
Hopefully 0.2.0 provides all of the features you need - certainly it still needs some improvement but it shows significant progress from earlier versions.
