### ISSUE TITLE
Parsing local_base_path

### ISSUE THREAD

**Issue by theflakes** [lilopkins/lnk-rs#11]
Thanks again for this crate, using it here: https://github.com/theflakes/fmd

Hoping it's a simple add to include the local_base_path field parsing from the lnk header and any other fields?

If I get time, I'll look into extending this crate as well but its beyond my capabilities atm. Still a lot to learn.

thanks again

**Comment by lilopkins** [comment]
Hi!

I'm actually working now on finishing the remainder of the parsing in the library - there were certainly some shortcomings previously in how some things were dealt with (read: strings).

There should be an update later that -- at least on my systems -- correctly reads the `local_base_path`. In fact, as I write this I am just working on the numerous `ExtraData` sections.

**Comment by theflakes** [comment]
Nice work and thanks so much for all the work on this. I've used it previously to parse links files referenced in the Windows registry. Finding it useful for this file forensics tool I'm trying to finish.

**Comment by lilopkins** [comment]
This should be fixed with release `lnk = "0.5.0"`. If the problem still persists afterwards, please provide a shell link file that doesn't work and I can investigate further!
