### ISSUE TITLE
Hotkey

### ISSUE THREAD

**Issue by theflakes** [lilopkins/lnk-rs#5]
This is probably a dumb question and I apologize.

How do I convert the hotkey and hotkey modifier to the enum values in HotkeyKey and HotkeyModifiers?

I'm not a dev, I just hack operational stuff.

thanks again

**Comment by lilopkins** [comment]
No question is a dumb question!

Assuming you just need to read the hotkey, with a valid `ShellLink` loaded in the variable `shortcut`:
```rs
let hotkey = shortcut.header().hotkey();
let key = hotkey.key();
let mods = hotkey.modifiers();

// key is now of the enum type HotkeyKey
// mods is now of the bitflag type HotkeyModifiers
```
At this stage, the `key` is hopefully self-explanatory as a [`HotkeyKey`](https://docs.rs/lnk/0.3.0/lnk/enum.HotkeyKey.html), and can be dealt with in all the usual ways enums. As for `mods`, it is important to consider that as it is a bitflag, multiple 'variants' can be active simultaneously. It would be worth looking through the available functions for [`HotkeyModifiers`](https://docs.rs/lnk/0.3.0/lnk/struct.HotkeyModifiers.html), particularly at [`contains`](https://docs.rs/lnk/0.3.0/lnk/struct.HotkeyModifiers.html#method.contains).

**Comment by theflakes** [comment]
Thanks,

Can you give me an example of how to take the hotkey.key() and hotkey.modifiers and translate them to their english Enum equivalents?

I understand how .key and .modifiers are stored, just not sure how to translate them easily to the named constants in the enums.  Sorry and thanks. Do I need to use a match statement?

**Comment by lilopkins** [comment]
Ah, I understand.
This has been a problem that I've had myself before, and the solutions are often not the most elegant. It seems like there are a variety of approaches people take, but there are some promising looking crates. One I have used before is [parse-display](https://crates.io/crates/parse-display), although I appreciate that this would need to be implemented at crate-level.
If this looks like it would be useful, I could implement it, however it is possible, depending on your use case, that a `match` statement returning a `&str` in each branch would be more suitable.

**Comment by theflakes** [comment]
Thanks, I can do the match statement. Been a while, but just need to figure out how to break the two bytes apart to get the key and key modifier. Been a while since I've done something like that.

Basically all I'm trying to do is make it human readable for security analysts to make it easier to work with in hunting / investigative tools.

Thanks again.

**Comment by lilopkins** [comment]
If you don't need it to be cleanly displayed, but just human readable then all the types implement `Debug`, so you could save some time just using `println!("{:#?}", hotkey);`, but this will depend on how clean you want your final interface to be!

**Comment by theflakes** [comment]
nice, will give that a try

**Comment by theflakes** [comment]
That does the job nicely, thanks so much! I should have known this too as I've used the debug output with format to get stuff into json previously.

**Comment by theflakes** [comment]
Again, thanks for this crate.

If you're interested, here's the project I used it in: https://github.com/theflakes/reg_hunter

Not a professional dev so my code is probably lacking.
