### ISSUE TITLE
Some lnks are not parsed

### ISSUE THREAD

**Issue by cyberpunkbln** [lilopkins/lnk-rs#9]
Hello,

lnks that i made with windows 10 don't have some informations like icon_location. Lnks that be made from the install program it one, have all correct infos.

[example_lnks.zip](https://github.com/lilopkins/lnk-rs/files/10304450/example_lnks.zip)

thx

**Comment by cyberpunkbln** [comment]
aahh i think i have the bug:

when i made a link with windows he don't write extra information that the icon is the exe, only when i update the icon (reselect) or use another icon. Is it possible to catch that? When has icon location : false then set path/file as icon location or so?

thx

**Comment by theflakes** [comment]
Thanks for this crate.

I'm having a problem getting the target of a lnk created on Windows 11 as well. I do see a "local_base_path" attribute when I print out the entire lnk structure. Not sure how to get at it atm though.

I was using the "relative_path" to get this but it's not being set it seems.

Thanks again for this crate.

**Comment by theflakes** [comment]
Found the issue for my problem anyways. If the lnk points to a file not on a different drive, the "relative_path" will be None. If the target is on the same drive, all is fine with that "relative_path" field.

**Comment by lilopkins** [comment]
At the moment, creating links is very unstable as still some of the structures for a lnk file are not present. Any breakthroughs about creating links would be particularly useful to document to help improve the functionality of  `ShellLink::new_simple`

**Comment by lilopkins** [comment]
This should be fixed with release `lnk = "0.5.0"`. I have tried to check both and both seem to parse some kind of file path to work with!
